### ISSUE TITLE
change all api.gresb.com URLs which point to the UI to portal.gresb.com

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#101]
Since the api-split is almost live we will no longer support any UI functionalities on api.gresb.com.

As such we need to change any reference to the UI in this URL to portal.gresb.com.

We partly did so in https://github.com/GRESB/api-docs/pull/89 but haven't covered all instances.

![image](https://user-images.githubusercontent.com/29230216/167652502-3dbbe4ee-c1d2-4d25-ba05-ada878bf0f7c.png)

_Originally posted by @joeyhorst in https://github.com/GRESB/api-docs/issues/89#issuecomment-1122472741_

**Comment by GokceBaykan** [comment]
done in #112
