### ISSUE TITLE
Survey opening and closing

### ISSUE THREAD

**Issue by EmilTemirov** [GRESB/api-docs#12]
I found that for 2014 Survey opening is 1st April, and closing is 1st July. Are those dates constant? If not, then can you implement and provide API for obtaining these dates?

**Comment by amichal** [comment]
We are doing this. There will be new properties on response documenting the necessary survey dates. Going live on the sandbox in the next day or so.

**Comment by amichal** [comment]
The response to `/api/responses/:id` now includes the `survey_period_opens_on` and `survey_period_closes_on` under a `survey` subresource
```json
{
  "id": 777583418,
  "survey_date": "2015",
  "name": "Example Response 1",
  "submitted_at": null,
  "manager": null,
  "region": null,
  "country": null,
  "property_type": null,
  "legal_status": null,
  "created_at": "2015-03-17T21:57:24Z",
  "updated_at": "2015-03-17T21:57:24Z",
  "company_fund_id": 124628267,
  "survey": {
    "title": null,
    "survey_period_opens_on": "2015-04-01T00:00:00Z",
    "survey_period_closes_on": "2015-09-30T00:00:00Z"
  }
}
```
