### ISSUE TITLE
Update api-docs with 2023 Assessment changes

### ISSUE THREAD

**Issue by GokceBaykan** [GRESB/api-docs#133]
2023 Real Estate Assessment has a series of changes made to it compared to the last year. These include introduction of new checkboxes, indicators, rules, etc. Next to this, examples of asset-level requests in our collection refer to previous reporting year, where performance data is outdated.

In light of new assessment:

- [x] Change the years in the content of the Postman Collection.
- [x] Introduce 2023 Assessment changes to the collection: Add new requests for new indicators and datapoints. Ensure that rule changes such as making % of Asset Ownership mandatory is accounted for.
- [x] Address the above point in the JSON examples of the documentation.

**Comment by joeyhorst** [comment]
already opened https://github.com/GRESB/api-docs/issues/129 for the % ownership

Let's focus on portfolio endpoint updates and asset endpoint updates separately 👍

**Comment by haya-mahmoud** [comment]
Test cases listed [here](https://github.com/GRESB/test-automation/issues/216#issuecomment-1447972668) are for the changes indicators. You can update the endpoints directly from theses.
