### ISSUE TITLE
Survey Access: Invite user problem

### ISSUE THREAD

**Issue by EmilTemirov** [GRESB/api-docs#14]
I tried to invite users to my survey on gresb-sandbox, but got following error message:
```
Access must be one of; invited user and account manager
```

**Comment by amichal** [comment]
Thanks for reporting this. The invite workflow is part of some code that is being refactored for 2015. We have the issue logged and once the refactored code is complete I'll update you here.

**Comment by amichal** [comment]
This is now fixed and deployed to https://api-sandbox.gresb.com
