### ISSUE TITLE
Only include whitelisted variables in the Real Estate Assessment variable list for data partners

### ISSUE THREAD

**Issue by GokceBaykan** [GRESB/api-docs#148]
We have variables which are not available to data partners' access. Instead of blacklisting those, we have whitelisted the remaining. Refer to the image below for a brief explanation on the portfolio variable whitelisting.

<img width="690" alt="Screenshot 2023-08-01 at 08 44 34" src="https://github.com/GRESB/api-docs/assets/100768664/78664a43-d79f-4c4c-ac9b-63cfbfe4e1eb">

We should ideally align our variable list in [this file](https://gresb-prd-public.s3.amazonaws.com/2023/data-partners/2023-real-estate-variables.xlsx) with the whitelist, meaning all variables like LE_1_Score needs to be removed from the file. It is up to the person picking up the task to decide if we should remove R_1.1_TBL from the file, or add a note that this is not a full path on its own.

The file then needs to be uploaded back to the same place in S3.

**Comment by joeyhorst** [comment]
Based on a comment in https://github.com/GRESB/api-docs/pull/147#discussion_r1280187929

**Comment by GokceBaykan** [comment]
The file can be found [here](https://gresbbv.sharepoint.com/:x:/s/SharedFiles/EcQVL8KPsv9CvnbiTuXJYgoBldHsdlv1p5GjxeQxbScRKQ?e=emjr6i). Old version is preserved within the same folder.

What has been changed?
- Removed scoring variables and other blacklisted endpoints.
- Marked the base patterns and aggregated values as such.
- Introduced more example for tables.
- Removed colouring from indicators added in 2023.
- Added other notes and fixed table stylings.

**Comment by joeyhorst** [comment]
Will be done as part of https://app.clickup.com/t/8693dcawg for 2024. For which we can use the work done by @GokceBaykan as a starting point
