### ISSUE TITLE
Add new datapoint Interim Target(%) to collection and Api documentation

### ISSUE THREAD

**Issue by lyusupova** [GRESB/api-docs#150]
" Interim There is a table about Year.
However, according to the https://documents.gresb.com/generated_files/real_estate/2023/real_estate/reference_guide/complete.html document, it can be confirmed that Interim Year and Interim Target exist as shown in the photo below (new question 2_(2)).
I can't find the API for Interim Target in postman, so I don't know what Endpoint is. Can I know the API information?
I know that Interim Year can be done using {{V0}}/entities/{{entity_id}}/responses/{{response_id}}/values/T_1.2_A1_TBL_ITR_1.
What I'm curious about is the API information about Interim Target(%).
If you check the https://documents.gresb.com/generated_files/real_estate/2023/real_estate/reference_guide/complete.html document, Interim Target(%) exists.
However, when I checked the https://gresb-prd-public.s3.amazonaws.com/2023/data-partners/2023-real-estate-variables.xlsx document and Postman, I could not find information about Interim Target(%). Please provide API information."

we have no endpoint for Interim %

**Comment by joeyhorst** [comment]
Which indicates we have to add `T_1.2_A1_TBL_ITRT_{index}` to the whitelisted variables.

Note that the index starts at `0` and not `1`. We can add 100 row indexes to be sure that the data partner can alter 100 rows if needed.

![image](https://github.com/GRESB/api-docs/assets/29230216/5b975e65-40b9-4fa8-b853-fbb1934c6e90)

While we're add it we can ensure that the other fields for `T_1.2_A1_TBL` are correctly whitelisted.

**Comment by joeyhorst** [comment]
done
