### ISSUE TITLE
Differentiate between string and numeric datatypes

### ISSUE THREAD

**Issue by GokceBaykan** [GRESB/api-docs#151]
Postman collection should be revised to change strings to number when the field expects number as datatype. This will eliminate the confusion arising among API users.

**Comment by joeyhorst** [comment]
Does this happen for the `/responses` endpoints or `/assets`? You have examples of where this happens? In general all values are stored as string in the `/responses` endpoints.

**Comment by GokceBaykan** [comment]
Most recent question was for portfolio level, but it was also asked for asset level before. My concern is that, while the portal accepts string through the response, we are sometimes actually expecting a number as answer. So if the question is asking about area certified, and API users submit "No area certified" instead of "0", the validation in the UI will complain "'No area certified' is not a number". For this my idea was to remove the quotation marks from the variable answer in the body of the requests in our collection, for wherever response expects a number. Because it seems the confusion is coming from that. But I also get that it is effort to differentiate these while the endpoint itself stores them all as strings.

**Comment by joeyhorst** [comment]
conclusion, `responses` endpoint doesn't has any validation, as such it won't inform the user what the required data type should be
