### ISSUE TITLE
Handling of partners_id field in asset data

### ISSUE THREAD

**Issue by brunogirin** [GRESB/api-docs#17]
There is a partners_id field in asset data that is meant to be unique. Is that ID meant to always be the same for the same asset? I.e. if I fill in the 2015 survey and have 12345 for a given asset, is the expectation that the same ID will be kept when I will in the 2016 survey next year?

**Comment by amichal** [comment]
It must be unique per response/survey year but not across survey years (over time). It could be but we have not yet established criteria for when an asset that may be renovated/expanded or repurposed for a different property_type would be considered a "new" asset so we make no assumptions that the partner_id will uniquely represents a building over timeframes longer then a year.

**Comment by amichal** [comment]
@brunogirin Assuming this makes sense to you now. If not feel free to reopen
