### ISSUE TITLE
How to obtain user credentials

### ISSUE THREAD

**Issue by brunogirin** [GRESB/api-docs#2]
The API requires authentication via OAuth2.0. It would be good to specify how user credentials can be obtained and whether an OAuth token is provided when authentication is successful.

**Comment by amichal** [comment]
Does the documentation here: http://gresb.github.io/api-docs/#api-authorization work for you? It assumes you have registered an account already (which i know we had issues if in your #8 issue)

**Comment by brunogirin** [comment]
Yes, this works so far. I've logged in and created the application. We'll do a test connection in the coming week.

**Comment by amichal** [comment]
All set i think
