### ISSUE TITLE
Links to the list of GRESB constants are not available by now

### ISSUE THREAD

**Issue by EmilTemirov** [GRESB/api-docs#23]
I'm trying to parse Response Legal Status value, earlier in the documentation of list of GRESB constants this field had integer value:

**Legal Status (GRESB)**

Name | Code
-------- | -------
Listed | 1
Non-listed | 2

So, I got an exception because actually the GRESB API returns string value for this field: "Listed" and "Non-listed". Then I tried to check this on the GRESB site, earlier all of GRESB constants were available by two links:

* https://www.gresb.com/about/lists
* https://www.gresb.com/mocks/lists

These links are not available by now.

**Comment by amichal** [comment]
These are back now. Looks like we broke that page in the rush to launch the survey.

**Comment by EmilTemirov** [comment]
Thanks, links are work now, but value of "Legal Status" still are returning as Title instead of Code.
I'm getting response:
``` javascript
{
    "object": "list",
    "has_more": false,
    "data": [
        {
            "country": null,
            "created_at": "2015-04-14T07:36:50Z",
            "id": 3001,
            "legal_status": "Listed",
            "manager": null,
            "name": "TestMe",
            "property_type": null,
            "region": null,
            "submitted_at": null,
            "survey_date": "2015",
            "updated_at": "2015-04-17T15:13:40Z"
        },
        {
            "country": null,
            "created_at": "2015-04-07T15:21:11Z",
            "id": 2855,
            "legal_status": null,
            "manager": null,
            "name": "responseTest6",
            "property_type": null,
            "region": null,
            "submitted_at": null,
            "survey_date": "2015",
            "updated_at": "2015-04-17T15:11:15Z"
        }
    ]
}
```
