### ISSUE TITLE
Asset Level Interface - how it works?

### ISSUE THREAD

**Issue by EmilTemirov** [GRESB/api-docs#24]
Could you please explain to me how *Assets* works in **Asset Level Interface**. 
First, I created *Response* and *Asset* via **GRESB API**, but I can't edit this *Asset* via **Asset Level Interface** - GRESB Site.
Second, *Assets* wich I have created via GRESB Site are invisible via **GRESB API**.

**Comment by amichal** [comment]
Just got off the phone with @brunogirin who should be able to explain this but in brief this behavior is as designed. 

1. Asset level data submitted through the API are only visible/editable by through the API. A user with access to the same response can see the data submitted through the API but the cannot directly edit it. 
2. Asset level data that comes through the interface (or through another API partner) is not visible in the API.

These rules are in place to prevent API partners for viewing each others data and to make it impossible to have a edit conflict in data submitted through the API while still allowing a GRESB user to have a complete view of all their data.

Tools exist within the site (but not the API) to allow end users to link data from multiple data sources (api partners or the 'Asset Level Interface' that represent the same asset/building
