### ISSUE TITLE
Different Legal Status value via Site and API

### ISSUE THREAD

**Issue by EmilTemirov** [GRESB/api-docs#26]
When I'm changing Legal Status via Site, I get no similar value via API occasionally:
![Legal Status via Site](http://emiltemirov.github.io/Images/images/legal_status_site.png)

API returns following:
```javascript
{
            "id": 3356,
            "survey_date": "2015",
            "name": "TestEmiEdited",
            "submitted_at": null,
            "manager": "EmiT",
            "region": null,
            "country": null,
            "property_type": null,
            "legal_status": "Non-listed",
            "created_at": "2015-04-24T09:29:39Z",
            "updated_at": "2015-04-24T15:15:41Z",
            "company_fund_id": 12658,
            "survey": {
                "survey_period_opens_on": "2015-04-01T00:00:00Z",
                "survey_period_closes_on": "2015-09-30T00:00:00Z"
            }
        }
```

Sometimes API returns a NULL in legal_status field, however this field was set on the site before.

**Comment by amichal** [comment]
I think this probably got you already but for the record: You should no longer be able to set this field. As of April 27 it should be read-only. It was our error that it was settable in the API at all. See: http://gresb.github.io/api-docs/#versioning for updates to the docs

**Comment by EmilTemirov** [comment]
Hi, Aaron. I don't try to change this field via API, I change it via gresb.com and get its value via API. But the value that I set via gresb.com and get via API are not the same sometimes.
