### ISSUE TITLE
Authorization request problem

### ISSUE THREAD

**Issue by NehalJ** [GRESB/api-docs#28]
Hi,

I am facing problem in step 1 request Authorization.  As per the GRESB API document, if user is not already signed into their GRESB account they will be probpted to sign in. Once signed in, the user will be shown an authotization request with the option to 'Authorize' or 'Deny' application access.

In my case, if user not logged in to the GRESB account,  sign in prompt is coming (As shown below in first picture) but once user signed in after that authorization request to 'Authorize' or 'Deny' application access is not coming but gives 'An error has occurred' 

I am using c# and asp.net 4.0 MVC to connect to the GRESB using below URL.

https://api-sandbox.gresb.com/oauth/authorize?client_id=ownClientId&redirect_uri=OwnRedirectURI&response_type=code&scope=edit_assets

I am redirecting to above url using window.location.href in JavaScript and after that below screen tosign in comes.(Attachment 1)

![image](https://cloud.githubusercontent.com/assets/13844995/10469902/b74adfe8-7254-11e5-888e-46af2d7c9461.png)

Once I will put credential and click on login after that below screen comes instead of 'Authorize' or 'Deny'

![image](https://cloud.githubusercontent.com/assets/13844995/10469916/dc1c0c3e-7254-11e5-9ca5-4871664fbc80.png)

Appreciate your help

Regards,

**Comment by NehalJ** [comment]
I am still waiting for the response for the above mentioned problem.

**Comment by amichal** [comment]
```
<html>
<head>
  <title>GRESB API Login Example</title>
  <script>
    var client_id = '29882b1a6d4e2281cddcd20004522d45cc84b9f0f7ae973330d6c42db5430600'
    var redirect_url = 'http://localhost:54795/Edge2/Index'
    function requestAccess() {
      window.location.href = 'https://api-sandbox.gresb.com/oauth/authorize?'
        +'client_id=' + escape(client_id)
        +'&redirect_uri='+ escape(redirect_url)
        +'&response_type=code&scope=edit_assets';
    }
  </script>
</head>
<body>
<a href='javascript:requestAccess()'>Request Access</a>
This example is not yet complete
</body>
</html>
```

**Comment by amichal** [comment]
I managed to reproduce and fix this problem today. It looks like a change we made to the login flow at the end of the 2014 survey period broke the work flow of authorizing a new API application when the user was not yet logged in. I'm deploying a fix now and will add a regression test to protect against this in the future
