### ISSUE TITLE
Field naming convention and lifetime of the API

### ISSUE THREAD

**Issue by brunogirin** [GRESB/api-docs#3]
The year is hard-coded in the field names. Does it mean that the API will necessarily change for the 2016 survey? In order to make the API (and everybody's work) re-usable, is there a way to use repeated blocks for each year with a common set of attributes?

For example, at the moment, the API mandates sending a structure like this:

```json
[ 
    {
    "building_id": 5756453454,
    "partner's_identifier": "asset 44",
    "asset_name": "Another Building",
    "asset_address": "900 Flat Street, Antarctica",
    "EN_WAR_MAN_BCF_ABS2013": 35342,
    "EN_WAR_MAN_BCF_ABS2014": 978675,
    "EN_WAR_MAN_BCF_COV2014": 12376,
    "EN_WAR_MAN_BCF_TOT2014": 45444,
    "EN_WAR_MAN_BCD_ABS2013": 15678
    }
]
```

It would be more modular to be able to send a structure like this one (or any similar variation):

```json
[ 
    {
    "building_id": 5756453454,
    "partner's_identifier": "asset 44",
    "asset_name": "Another Building",
    "asset_address": "900 Flat Street, Antarctica",
    "survey_data":
        {
        "2013":
            {
            "EN_WAR_MAN_BCF_ABS": 35342,
            "EN_WAR_MAN_BCD_ABS": 15678
            },
        "2014":
            {
            "EN_WAR_MAN_BCF_ABS": 978675,
            "EN_WAR_MAN_BCF_COV": 12376,
            "EN_WAR_MAN_BCF_TOT": 45444
            }
        }
    }
]
```

**Comment by amichal** [comment]
We have re-structured the JSON per your suggestion and are in the process of updating the documentation. I'll comment further on this issue when we get updated documentation deployed

**Comment by brunogirin** [comment]
Brilliant, thanks!
