### ISSUE TITLE
introduce nice line breaks into data dictionary

### ISSUE THREAD

**Issue by emmastorm** [GRESB/api-docs#51]
In the data dictionary table, some of the descriptions are very long. Add nice line breaks so that unit column doesn't get shoved to a new line.

I already tried to implement line breaks in the [dictionary.yml](https://github.com/GRESB/api-docs/blob/master/data/dictionary.yml) file itself, but it seemed not to work. Perhaps something in the css? html? markdown? formatting can be changed instead.

**Comment by emmastorm** [comment]
@gresbtim fixed this! ❤️

**Comment by joeyhorst** [comment]
👏 nicely done
