### ISSUE TITLE
update links in data dictionary when 2020 reference guide is ready

### ISSUE THREAD

**Issue by emmastorm** [GRESB/api-docs#52]
update links at bottom of [dictionary.yml](https://github.com/GRESB/api-docs/blob/master/data/dictionary.yml) when the 2020 reference guide is out.

**Comment by joeyhorst** [comment]
We can also refer to https://documents.gresb.com/index.html in the meanwhile

**Comment by joeyhorst** [comment]
@emmastorm, should we pick this up now?

**Comment by emmastorm** [comment]
oh ya good remembering

I'll put it on my to-do list

**Comment by emmastorm** [comment]
ok updated -- links were removed from the data dictionary definitions themselves at some point, so I added a link to the reference guide to the top of of the data dictionary section
