### ISSUE TITLE
asset_vacancy is still valid but it's shown as removed

### ISSUE THREAD

**Issue by teoulas** [GRESB/api-docs#57]
At the bottom where we list all changed columns `asset_vacancy` is in the removed ones:

![Screenshot_Τρι_2020-03-10_17-47-19](https://user-images.githubusercontent.com/53618/76337465-adc47900-62f7-11ea-86a0-3863a933aafd.png)

However, the column is still relevant. We have validations on it and it's also in the data dictionary table:
![Screenshot_Τρι_2020-03-10_17-48-00](https://user-images.githubusercontent.com/53618/76337538-ccc30b00-62f7-11ea-9b11-a24ab02ceb5e.png)

**Comment by Joanf81** [comment]
@teoulas So do we have to take it away from the removed hash?

**Comment by teoulas** [comment]
Yup - it's still used

**Comment by joeyhorst** [comment]
Very minor - @Joanf81 could you do this? - should be a 5min thing.

**Comment by stoutountzoglou** [comment]
I think @gresbtim aready handled this!

**Comment by gresbtim** [comment]
@joeyhorst 1.5 minutes till deployed. ;-)

**Comment by joeyhorst** [comment]
🚀
