### ISSUE TITLE
Batch Asset endpoint returns 500 error

### ISSUE THREAD

**Issue by augustwoodul** [GRESB/api-docs#62]
I'm getting a 500 error when POSTing the following JSON to the /assets/batches endpoint in the sandbox:

{"always_create":[],"create":[{"gresb_asset_id":null,"partners_id":"799423","optional_information":"","address":"24 Milton Road, Milton Keynes, Buckinghamshire, MK15 9JJ","city":"Milton Keynes","state_province":"Buckinghamshire","country":"GB","lat":52.0636417,"lng":-0.7202707,"construction_year":null,"annual_data":[{"year":2019,"asset_name":"Property 2","property_type_code":"INMA","owned_entire_period":true,"ownership_from":null,"ownership_to":null,"en_data_from":"2019-01-01","en_data_to":"2019-12-31","wat_data_from":"2019-01-01","wat_data_to":"2019-12-31","was_data_from":"2019-01-01","was_data_to":"2019-12-31","whole_building":"0","asset_size_common":"110","asset_size_shared":"120","asset_size_tenant":"90","asset_size_tenant_landlord":"40","asset_size_tenant_tenant":"50","en_abs_wf":"53","en_cov_wf":"68","en_tot_wf":"88","en_abs_wd":"51","en_cov_wd":"66","en_tot_wd":"86","en_abs_we":"52","en_cov_we":"67","en_tot_we":"87","en_abs_lc_bsf":"40","en_cov_lc_bsf":"22","en_tot_lc_bsf":"41","en_abs_lc_bsd":"38","en_cov_lc_bsd":"20","en_tot_lc_bsd":"39","en_abs_lc_bse":"39","en_cov_lc_bse":"21","en_tot_lc_bse":"40","en_abs_lc_bcf":"37","en_cov_lc_bcf":"19","en_tot_lc_bcf":"76","en_abs_lc_bcd":"35","en_cov_lc_bcd":"17","en_tot_lc_bcd":"74","en_abs_lc_bce":"36","en_cov_lc_bce":"18","en_tot_lc_bce":"75","en_abs_lc_tf":"45","en_cov_lc_tf":"25","en_tot_lc_tf":"25","en_abs_lc_td":"43","en_cov_lc_td":"23","en_tot_lc_td":"23","en_abs_lc_te":"44","en_cov_lc_te":"24","en_tot_lc_te":"24","en_abs_tc_tf":"50","en_cov_tc_tf":"28","en_tot_tc_tf":"28","en_abs_tc_td":"48","en_cov_tc_td":"26","en_tot_tc_td":"26","en_abs_tc_te":"49","en_cov_tc_te":"27","en_tot_tc_te":"27","en_abs_tc_of":"47","en_abs_tc_oe":"46","en_ren_ons_con":"71","en_ren_ons_exp":"72","en_ren_ons_tpt":"73","en_ren_ofs_pbl":"69","en_ren_ofs_pbt":"70","ghg_abs_s1_w":"102","ghg_cov_s1_w":"109","ghg_tot_s1_w":"112","ghg_abs_s1_o":"101","ghg_abs_s2_lb_w":"104","ghg_cov_s2_lb_w":"110","ghg_tot_s2_lb_w":"113","ghg_abs_s2_lb_o":"103","ghg_abs_s2_mb_w":"106","ghg_abs_s2_mb_o":"105","ghg_abs_s3_w":"108","ghg_cov_s3_w":"111","ghg_tot_s3_w":"114","ghg_abs_s3_o":"107","ghg_abs_offset":"100","wat_abs_w":"307","wat_cov_w":"50","wat_tot_w":"200","wat_abs_lc_bs":"302","wat_cov_lc_bs":"309","wat_abs_lc_bc":"301","wat_cov_lc_bc":"308","wat_abs_lc_t":"304","wat_cov_lc_t":"310","wat_abs_tc_t":"306","wat_cov_tc_t":"311","wat_abs_lc_o":"303","wat_rec_ons_reu":"316","wat_rec_ons_cap":"314","wat_rec_ons_ext":"315","wat_rec_ofs_pur":"313","was_abs_haz":"201","was_abs_nhaz":"202","was_pcov":"41","was_pabs_lf":"11","was_pabs_in":"10","was_pabs_ru":"14","was_pabs_wte":"40","was_pabs_rec":"13","was_pabs_oth":"12","en_emr_wdr":"1","wat_emr_tba":"0","wat_emr_amr":"1","wat_emr_clt":"0","wat_emr_dsi":"1","wat_emr_dtnl":"0","wat_emr_hedf":"1","wat_emr_lds":"0","wat_emr_mws":"1","wat_emr_owwt":"0","wat_emr_rsgw":"1","was_emr_tba":"0","was_emr_clfw":"1","was_emr_opm":"0","was_emr_rec":"1","was_emr_wsm":"0","was_emr_wsa":"1","en_emr_tba":"0","en_emr_amr":"0","en_emr_asur":"1","en_emr_msur":"0","en_emr_ihee":"0","en_emr_iren":"1","en_emr_oce":"1","en_emr_sbt":"0","en_emr_src":"1","en_emr_wri":"0","construction_year":"2003","asset_gav":"1","asset_size":"200","tenant_ctrl":"0","asset_vacancy":"4","ncmr_status":"Major Renovation Project","ncmr_from":"2019-01-03","ncmr_to":"2019-02-03"}],"created_at":null,"updated_at":null,"_validations":null}],"always_update":[],"update":[],"delete":[]}

The error has the content:
"{\"error\":\"500 - Server error: undefined method `en_abs_lc_bde' for #<BuildingData::BuildingRow:0x000055f6176a1838>\\nDid you mean?  en_abs_lc_bse\\n               en_abs_lc_bsd\\n               en_abs_lc_bce\\n               en_abs_lc_bcd\\n               en_abs_lc_bce?\\n               en_abs_lc_bce=\\n               en_abs_lc_bcd?\\n               en_abs_lc_bcd=\\n               en_abs_lc_bse?\\n               en_abs_lc_bse=\\n               en_abs_lc_bsd?\\n               en_abs_lc_bsd=\\n               en_abs_lc_we\\n               en_abs_lc_wd\\n               en_abs_lc_oe\\n               en_abs_lc_te\\n               en_abs_lc_td\\n               en_abs_lc_oe?\\n               en_abs_lc_oe=\\n               en_abs_lc_te?\\n               en_abs_lc_te=\\n               en_abs_lc_td?\\n               en_abs_lc_td=\\n               en_abs_lc_we?\\n               en_abs_lc_we=\\n               en_abs_lc_wd?\\n               en_abs_lc_wd=\\n               en_abs_lc_bsf\\n               en_abs_lc_bcf\\n               en_abs_lc_bcf?\\n               en_abs_lc_bcf=\\n               en_abs_lc_bsf?\\n               en_abs_lc_bsf=\\n               en_abs_tc_we\\n               en_abs_tc_wd\\n               en_abs_lc_wf\\n               en_abs_tc_oe\\n               en_abs_lc_of\\n               en_abs_tc_te\\n               en_abs_tc_td\\n               en_abs_lc_tf\\n               en_abs_tc_oe?\\n               en_abs_tc_oe=\\n               en_abs_lc_of?\\n               en_abs_lc_of=\\n               en_abs_tc_te?\\n               en_abs_tc_te=\\n               en_abs_tc_td?\\n               en_abs_tc_td=\\n               en_abs_lc_tf?\\n               en_abs_lc_tf=\\n               en_abs_tc_we?\\n               en_abs_tc_we=\\n               en_abs_tc_wd?\\n               en_abs_tc_wd=\\n               en_abs_lc_wf?\\n               en_abs_lc_wf=\\n               en_abs_tc_wf\\n               en_abs_tc_of\\n               en_abs_tc_tf\\n               en_abs_tc_of?\\n               en_abs_tc_of=\\n               en_abs_tc_tf?\\n               en_abs_tc_tf=\\n               en_abs_tc_wf?\\n               en_abs_tc_wf=\\n               en_tot_lc_bse\\n               en_tot_lc_bce\"}"

But we're not sending en_abs_lc_bde, and it doesn't seem to be in the data dictionary - maybe there's a typo somewhere or the sandbox api is out of date?

Please let me know if there's anything else I can provide to help diagnose this.

Best,
August

**Comment by gresbtim** [comment]
hi @augustwoodul 
thanks for reporting, it's indeed a bug on our side, we will fix it and have it deployed in around 30 minutes.
