### ISSUE TITLE
Validation endpoint returns string for asset_size and certification size

### ISSUE THREAD

**Issue by gwgrubbs** [GRESB/api-docs#68]
The data dictionary specifies a data type of numeric for certification "size" and annual data "asset_size", but validation errors returned from
```
[POST] /api/v1/entities/{entityId}/assets/validation
```
return the values as strings.

Expected: 1757330.0
Actual: "1757330.0"

**Comment by gresbtim** [comment]
hi @gwgrubbs 

thanks for reporting this, we rolled out a fix.
