### ISSUE TITLE
Batch_asset endpoint update rejects updates to assets with invalid annual data for years not being sent

### ISSUE THREAD

**Issue by augustwoodul** [GRESB/api-docs#69]
When we send updates for 2018 and 2019 via the batch_asset endpoint in the update section, and there is 2017 data with validation errors, we get an invalid count of 2, even though the 2018 and 2019 data is valid. Is it expected that invalid 2017 data would stop the update of 2018 and 2019 data in this case? 

If so, is there a way to have the API only validate the data sent (we still want to notify the user if there are validation issues with what is being sent for 2018 and 2019, but they've indicated they don't want to fix 2017 data before providing 2018 and 2019 data)?

**Comment by gresbtim** [comment]
hey @augustwoodul can you pls send me example request to t.kretschmer@gresb.com ? Thanks!

**Comment by gresbtim** [comment]
hi @augustwoodul 
we identified the issue and will roll out a fix soon. thanks for reporting this!
