### ISSUE TITLE
Typo reporting_period

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#75]
In the request example there is a typo: https://gresb.github.io/api-docs/#reporting-entities

![image](https://user-images.githubusercontent.com/29230216/101652761-ea680100-3a3e-11eb-9658-566db84d821f.png)

**Comment by joeyhorst** [comment]
@naincygoyal also in the example presented in the api-docs? It never was an issue in the api response, mainly in the documentation.

**Comment by naincygoyal** [comment]
@joeyhorst I have committed these changes in code.
