### ISSUE TITLE
asset_ownership is stored as a text where it should be a numerical value

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#79]
![image](https://user-images.githubusercontent.com/29230216/112286492-ab775780-8c8b-11eb-9724-3acf9f4ef878.png)

**Comment by naincygoyal** [comment]
@joeyhorst Below scenarios to test :

- [ ] "asset_ownership" with integer value

<details>
<summary> Integer value </summary>

![image](https://user-images.githubusercontent.com/97026424/156592892-a6074277-1f4c-4c4d-8cdc-b875a1839d51.png)

</details>

- [ ] "asset_ownership" with string value
<details>
<summary> String value </summary>

![image](https://user-images.githubusercontent.com/97026424/156593257-d0eab11a-21c4-428d-b4f6-03cc97fdbee9.png)

</details>

It seems it has not fixed yet.

**Comment by joeyhorst** [comment]
@jjpai we can open a ticket for the devs to tackle data types in general. It would have a low priority though as it doesn't affect the functionality of the GRESB Asset Portal.

**Comment by joeyhorst** [comment]
Let's keep it as is as it doesn't affect the integrity of the api requests (just the datatype).

**Comment by joeyhorst** [comment]
Same happens for `asset_size` in the request. api indicates it's a string, but when creating a new asset it requires a number.

Relates to https://github.com/GRESB/api-docs/issues/68.
