### ISSUE TITLE
Cannot go past T&C in registration on sandbox

### ISSUE THREAD

**Issue by brunogirin** [GRESB/api-docs#8]
When I try to register on the sandbox system, it keeps asking me to accept the T&C. I check the check box but it comes back with an error:

Step 1: tick the check box and click submit:
![mozilla firefox_718](https://cloud.githubusercontent.com/assets/216028/5724242/45139db4-9b42-11e4-98e2-4ea89477f809.png)

Step 2: error at top of screen asking to accept T&C
![mozilla firefox_719](https://cloud.githubusercontent.com/assets/216028/5724245/486d836c-9b42-11e4-83ff-c06158d5c998.png)

**Comment by amichal** [comment]
This is fixed now... sorry about that
