### ISSUE TITLE
swagger file is outdated

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#80]
![image](https://user-images.githubusercontent.com/29230216/112318201-12593880-8cad-11eb-9637-ecd84464e4b0.png)

https://api.gresb.com/api/v1/swagger_doc

**Comment by joeyhorst** [comment]
@stoutountzoglou main thing is that when we read the swagger file it states:

`{"info":{"title":"GRESB asset-level data API","version":"0.90"}`

Although we're no longer on version 0.90, we're at version 1.01: http://gresb.github.io/api-docs/#api-version-history

So see in the code where we generate the file and update it 👍

**Comment by stoutountzoglou** [comment]
Linked PR:
https://github.com/GRESB/gresb-reports/pull/15976

**Comment by stoutountzoglou** [comment]
@joeyhorst this is ready on my side, we are just investigating some PR env issues with Miguel and I'll let you know when you could test it.

In the end `swagger_doc` isn't stored anywhere, it's generated on the fly each time one visits https://api.gresb.com/api/v1/swagger_doc

After changing the version from `0.9` to `1.01`, and importing the json generated to Postman/Insomnia, I didn't notice any differences, meaning the api imported requests were always working as should. 
What has changed for this ticket in the end is what you're claiming on the [comment](https://github.com/GRESB/api-docs/issues/80#issuecomment-990000373) above, which now is:
`{"info":{"title":"GRESB asset-level data API","version":"1.01"}`

**Comment by joeyhorst** [comment]
@stoutountzoglou that's re-assuring to hear. Also means it will have a bigger impact if we change base URLs / endpoints from one version to another, but in this case data partners wouldn't have faced any issues. 👍

**Comment by stoutountzoglou** [comment]
@joeyhorst here you go:
https://gresb-reports-pr15976.eu-central-1.elasticbeanstalk.com/api/v1/swagger_doc

I don't think it's worth the hassle of going down the DETAP street, but let me know what you think

**Comment by joeyhorst** [comment]
I agree, let's just move this to prod.

Closing the issue as this repo is publicly available and we merge the PR in another repo 👍
