### ISSUE TITLE
Check if api.gresb.com/api/v1 is still the correct base URL for production

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#85]
In http://gresb.github.io/api-docs/#basic-operations-endpoints, we refer to https://api.gresb.com/api/v1 as the production endpoint. This is/was? the URL to use for submitting the real estate asset data via the API.

Receiving some questions from data partners why it is not accessible from the browser. Will refer them to https://portal.gresb.com/oauth/applications for prod and https://api-sandbox.gresb.com/oauth/applications for sandbox.

Check if the following URL is still used for the production API endpoint? If not then change the api-docs accordingly.

```
curl https://api.gresb.com/api/v1/entities/5028/assets \
  -H "Authorization: Bearer $ACCESS_TOKEN"
```

**Comment by joeyhorst** [comment]
@apostolosSotiropoulos @miguelaferreira till recently api.gresb.com was accessible. Do you know what the correct base URL is for production endpoints?

**Comment by miguelaferreira** [comment]
That domain name was not updated while migrating the production portal. I've updated now, it should be reachable again. If not immediately, within the hour all DNS caches should have been invalidated and the resolution should work again.

**Comment by joeyhorst** [comment]
Beautiful - thanks for updating @miguelaferreira 👍
