### ISSUE TITLE
verify if all request examples still work in the api-docs

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#88]
as the title mentioned, we should run though the examples and make sure they are all valid

**Comment by naincygoyal** [comment]
I will test following request

- [] POST Request to create single asset
- [] GET Request to retrieve single asset.
- [] Patch request to update single asset
- [] Delete request to delete an asset
- [] Get Request to retrieve an asset in batch
- [] Delete request to delete an asset in batch ("delete")
- [] PATCH Request to update an asset in batch ( "always_update")
-
---

**Comment by joeyhorst** [comment]
@naincygoyal believe we need to cover all code blobs on the right hand side of the api-docs - such as http://gresb.github.io/api-docs/#users, etc. This also includes simple GET requests.

**Comment by naincygoyal** [comment]
Yes Joey even Certification and Energy need to add ...I will  first finish asset then will pick user, energy , certification etc and will update in the same list.

**Comment by naincygoyal** [comment]
@joeyhorst  https://github.com/GRESB/api-docs/issues/88#issuecomment-1049779332 in this comment I mentioned PATCH and DELETE in batch is not working , could you please once and confirm why its not working ?

**Comment by joeyhorst** [comment]
@naincygoyal The batch operation contains objects like "always_update" and "delete" to perform PATCH and DELETE methods. 

As such you will need to do this within the batch operation and not as a method.

The HTTPS method to use is POST.

**Comment by joeyhorst** [comment]
closing this as it is already in master but still needs to be published
