### ISSUE TITLE
No Validation Message when asset_gav is 0 besides able to report per asset.

### ISSUE THREAD

**Issue by naincygoyal** [GRESB/api-docs#92]
**Describe the bug**
Getting no validation message when giving 0 value for GAV besides according to report it needs to be report annual not per asset but currently I can give under Asset. Although it seems asset_gav does not have any impact on response.

**To Reproduce**
**Steps to reproduce the behaviour:**
1. Use POST Request in Postman to create an asset for entity 16286 - {{baseUrl}}/api/v1/entities/:entity_id/assets/ 

**Expected behaviour**
Response should throw an error on entering invalid value either 0 or string.

**Screenshots**

![image](https://user-images.githubusercontent.com/97026424/156596778-f17cb2c9-5dc9-4c4d-a04a-cff1622c4d97.png)

**Additional context**
I believe gav we can report per asset and api docs needs to be updated.

![image](https://user-images.githubusercontent.com/97026424/156596986-ac0cd375-4288-4678-90f4-1a05f85d8b0a.png)

**Comment by joeyhorst** [comment]
`asset_gav` is provided per asset as can be seen in:

<details>
<summary> the asset spreadsheet </summary>

![image](https://user-images.githubusercontent.com/29230216/156724512-db666245-505a-4462-a425-2fedd319ed3f.png)

</details>

<details>
<summary> and the Asset Portal UI </summary>

![image](https://user-images.githubusercontent.com/29230216/156724692-3010ed0a-1825-45eb-b161-a9b6b91de61f.png)

</details>

Not sure what you mean by:

>according to report it needs to be reported annual not per asset

---

>Response should throw an error on entering invalid value either 0 or string.

1. it should return a validation of the value is 0

<details>
<summary> error in the UI </summary>

![image](https://user-images.githubusercontent.com/29230216/156725060-2b536ea4-897d-440c-a198-b5a0a37f5497.png)

</details>

2. in the UI it doesn't allow the user to enter "abc" as it only alllows numerical values. As it is an optional field the API will simple disregard the string and not throw an error. We should check 1. but the second issue is not a problem.

**Comment by naincygoyal** [comment]
I am closing this issue as its working fine.
