### ISSUE TITLE
take out years for the survey documentation reference

### ISSUE THREAD

**Issue by joeyhorst** [GRESB/api-docs#95]
The reference to the documentation says 2021, but I made sure last year that it would refer to our general documentation page: https://documents.gresb.com/. 

Would be good to check our docs for any 2021 reference and remove the year.

![image](https://user-images.githubusercontent.com/29230216/159234629-0da661a1-805a-4992-8cef-61a0b48070d8.png)

**Comment by GokceBaykan** [comment]
done in #112
